version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "r4b2"
      - "Xenion1987"
    groups:
      github-actions-update:
        patterns:
          - "*"
