name: docker-build

on:
  schedule:
    - cron: "20 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [created]

concurrency: docker-build-${{ github.ref }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container (push, workflow_dispatch, schedule)
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        id: meta-push
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ghcr.io/${{ github.repository }}
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=raw,value=latest,enable=true

      - name: Extract metadata for container (release created)
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        id: meta-release
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ghcr.io/${{ github.repository }}
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image latest (push, workflow_dispatch, schedule)
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          #platforms: linux/amd64
          tags: ${{ steps.meta-push.outputs.tags }}
          labels: ${{ steps.meta-push.outputs.labels }}
          provenance: false

      - name: Build and push image release (release created)
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          #platforms: linux/amd64
          tags: ${{ steps.meta-release.outputs.tags }}
          labels: ${{ steps.meta-release.outputs.labels }}
          provenance: false

      - name: Build image pull request (no push to ghcr)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: false
          platforms: linux/amd64
          provenance: false
