name: docker-build

on:
  schedule:
    - cron: "20 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [created]

concurrency: docker-build-${{ github.ref }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98

      - name: Login to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container (push, workflow_dispatch, schedule)
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        id: meta-push
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ghcr.io/${{ github.repository }}
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=raw,value=latest,enable=true

      - name: Extract metadata for container (release created)
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        id: meta-release
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ghcr.io/${{ github.repository }}
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image latest (push, workflow_dispatch, schedule)
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          #platforms: linux/amd64
          tags: ${{ steps.meta-push.outputs.tags }}
          labels: ${{ steps.meta-push.outputs.labels }}

      - name: Build and push image release (release created)
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          #platforms: linux/amd64
          tags: ${{ steps.meta-release.outputs.tags }}
          labels: ${{ steps.meta-release.outputs.labels }}

      - name: Build image pull request (no push to ghcr)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: false
          platforms: linux/amd64
